<option value="" selected></option>
<option value="isbn13">ISBN 13</option>
<option value="isbn10">ISBN 10</option>
<option value="jobname">JOBNAME</option>
<option value="filename">FILENAME</option>
<option value="doi">DOI</option>
<option value="issn">ISSN</option>
<option value="volume">VOLUME</option>
<option value="journalId">JOURNAL ID</option>
<option value="issue">ISSUE</option>
<option value="bookTitle">BOOK TITLE</option>
<option value="journalTitle">JOURNAL TITLE</option>
<option value="dateReceived">DATE RECIEVED</option>
<option value="dateEntered">DATE ENTERED</option>
<option value="boxFilename">BOX FILENAME</option>
<option value="shipmentNumber">SHIPMENT NO</option>
<option value="coverDate">COVER DATE</option>
<option value="copyrightYear">COPYRIGHT YEAR</option>
